name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install additional tools
      run: |
        pip install flake8 pytest autopep8 coverage codecov

    - name: Autoformat code with autopep8
      run: autopep8 --in-place --recursive .

    - name: Run flake8
      run: flake8 .

    - name: Run Django tests
      run: python3 manage.py test  

    - name: Run pytest with coverage
      run: |
        coverage run -m pytest -v
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: unittests
        name: codecov-umbrella
